test:
  adapter: postgresql
  encoding: unicode
  database: previewify_test
  pool: 5
  username: pg_test
  password: password


#  adapter: mysql
#  database: previewify_test
#  username: root
#  password:
#  host: localhost
